import { VOICES } from './voices.js'
// A namespace import rather than named ones, on purpose. calibration.js is
// generated by a tool that imports this file, so a named import of something
// the current calibration.js does not export yet is a syntax error that
// prevents the tool from running and regenerating it — a deadlock every time a
// voice is added. Unity is the right fallback: uncalibrated means "play it as
// written", not "fail".
import * as CAL from './calibration.js'
import {
  audioState,
  bed,
  configureAudio,
  createChain,
  dbToGain,
  hasPref,
  isAudible,
  setEnabled,
  sound,
  subscribe,
  teardownAudio,
  toggleEnabled,
} from '../../../audio/engine.js'

/**
 * This route's mix: which moments exist, what each sounds like, and exactly
 * how loud it ends up.
 *
 * The machinery — context, buses, ceiling, cooldowns, preference, unlock —
 * is `src/audio/engine.js`, shared with /construction-two. What lives here is
 * everything true of the knowledge tree and nothing else.
 *
 * THE STORY, AS A MIX
 *
 * The journey is seed → growth → disciplines → knowledge → connection →
 * mystery → discovery → future, and the table below is arranged in that order
 * so the emotional progression can be read straight down the peak column:
 *
 *   quiet      the seed chapter sits 10 dB under everything else
 *   growing    organic events enter, still under the interaction layer
 *   discovery  the museum is the densest section, and the most tactile
 *   connection two tones, panned, then one that resolves them
 *   mystery    the glimpse is the quietest thing after the seed
 *   revelation one event at −19, the loudest on the page by 3 dB
 *   future     back down to almost nothing
 *
 * If a sound is noticeable every time it happens it is too loud, so the
 * targets here are deliberately lower than construction-two's across the
 * board: that page is a film about building, this one is a room to think in.
 */

const CALIBRATION = CAL.CALIBRATION ?? {}
const AMBIENCE_TRIM = CAL.AMBIENCE_TRIM ?? 1
const DISTANT_TRIM = CAL.DISTANT_TRIM ?? 1
const GROWTH_TRIM = CAL.GROWTH_TRIM ?? 1
const WOOD_TRIM = CAL.WOOD_TRIM ?? 1
const LEAF_TRIM = CAL.LEAF_TRIM ?? 1
const CAMPUS_TRIM = CAL.CAMPUS_TRIM ?? 1
const AIR_TRIM = CAL.AIR_TRIM ?? 1

/* -------------------------------------------------------------------- mix */
const BUS_LEVELS = {
  ambience: 0.2,
  interaction: 0.3,
  organic: 0.25,
  knowledge: 0.25,
  transitions: 0.22,
}

const MASTER = 0.14

/** Sustained layers, in dBFS at the speaker. All three are felt, not heard. */
const AMBIENCE_PEAK = -42
const DISTANT_PEAK = -38
const GROWTH_PEAK = -36
// The four things that come into existence, and the air the camera moves
// through. These carry the page — a formation the reader is watching should
// not be silent, so these sit above the atmospheric beds rather than under
// them.
const WOOD_PEAK = -26
const LEAF_PEAK = -28
const CAMPUS_PEAK = -27
const AIR_PEAK = -29

/**
 * `peak` is the target peak AT THE SPEAKER in dBFS, after bus and master.
 * `calibration.js` is generated by `tools/calibrate_education_audio.mjs`,
 * which renders every sound below through this exact graph and works out the
 * correction that makes it hit the number written here. Change a voice or a
 * target, re-run the tool, commit the result.
 */
const SOUNDS = {
  /* 0 — seed. Almost silent: the quietest chapter on the page. ---------- */
  'seed.stir':     { voice: 'soil',        bus: 'organic',      peak: -34, cooldown: 900, vary: 0.2 },
  'seed.open':     { voice: 'seedOpen',    bus: 'organic',      peak: -26, cooldown: 2000, vary: 0.06 },

  /* 1 — growth. Milestones, never a per-frame stream. ------------------- */
  // Wood, leaves and the campus are FORMATIONS, not events — see the bed
  // section below. What is left here is the one thing that really is an
  // event: the roots taking hold.
  'grow.roots':    { voice: 'soil',        bus: 'organic',      peak: -30, cooldown: 1200, vary: 0.18 },

  /* props arriving. Five groups, five pitches, one phrase. --------------- */
  'prop.tung':     { voice: 'tung',        bus: 'knowledge',    peak: -25, cooldown: 90, vary: 0.04 },

  /* 2 — disciplines. One family, five characters. ----------------------- */
  // Each is a different voice but they share the band, the envelope length and
  // the level, which is what stops five disciplines sounding like five apps.
  'disc.technology':  { voice: 'technical', bus: 'knowledge', peak: -31, cooldown: 260, vary: 0.16, weight: 0.4 , hover: true },
  'disc.science':     { voice: 'glass',     bus: 'knowledge', peak: -32, cooldown: 260, vary: 0.14 , hover: true },
  'disc.design':      { voice: 'pencil',    bus: 'knowledge', peak: -31, cooldown: 260, vary: 0.18 , hover: true },
  'disc.engineering': { voice: 'mechanism', bus: 'knowledge', peak: -31, cooldown: 260, vary: 0.16 , hover: true },
  'disc.business':    { voice: 'tone',      bus: 'knowledge', peak: -33, cooldown: 260, vary: 0.05, step: -5, dur: 0.4 , hover: true },
  'disc.resolved':    { voice: 'resolution', bus: 'transitions', peak: -28, cooldown: 2500 },

  /* 3 — museum. The densest, most tactile section. ---------------------- */
  'museum.enter':  { voice: 'spatial',    bus: 'transitions',  peak: -27, cooldown: 1400, vary: 0.08 },
  'museum.stop':   { voice: 'page',       bus: 'knowledge',    peak: -28, cooldown: 500,  vary: 0.12 },
  'museum.settle': { voice: 'resolution', bus: 'transitions',  peak: -29, cooldown: 2500, rate: 1.2 },
  // Artifact focus. Three textures, chosen by what the object is made of.
  'artifact.paper': { voice: 'paper',     bus: 'knowledge',    peak: -33, cooldown: 220, vary: 0.2, hover: true },
  'artifact.glass': { voice: 'glass',     bus: 'knowledge',    peak: -34, cooldown: 220, vary: 0.16, hover: true },
  'artifact.tech':  { voice: 'technical', bus: 'knowledge',    peak: -33, cooldown: 220, vary: 0.2, weight: 0.3, hover: true },

  /* 4 — connection. Two sides, then one. -------------------------------- */
  // The pan is the idea: the two halves arrive from opposite places and the
  // resolution arrives from neither. Subtle enough not to be noticed as an
  // effect, which is the brief.
  'connect.left':  { voice: 'tone', bus: 'transitions', peak: -31, cooldown: 2200, step: 0,  pan: -0.55, dur: 0.9 },
  'connect.right': { voice: 'tone', bus: 'transitions', peak: -31, cooldown: 2200, step: 7,  pan: 0.55,  dur: 0.9 },
  'connect.join':  { voice: 'tone', bus: 'transitions', peak: -29, cooldown: 2200, step: 12, dur: 1.4 },

  /* 5 — glimpse. Quieter than everything except the seed. --------------- */
  'glimpse.sense': { voice: 'revealResonance', bus: 'ambience', peak: -33, cooldown: 3000, rate: 1.35 },

  /* 6 — reveal. The one large moment, and still restrained. ------------- */
  'reveal.open':   { voice: 'spatial',         bus: 'transitions', peak: -26, cooldown: 2000, dur: 0.9 },
  'reveal.campus': { voice: 'revealResonance', bus: 'transitions', peak: -19, cooldown: 6000 },
  'reveal.near':   { voice: 'leaf',            bus: 'organic',     peak: -31, cooldown: 700, vary: 0.2 },

  /* 7 — future. Simplify, then stop. ------------------------------------ */
  'future.settle': { voice: 'resolution', bus: 'transitions', peak: -30, cooldown: 4000, rate: 0.85 },

  /* interface. One family for everything a pointer touches. ------------- */
  'ui.click':      { voice: 'technical', bus: 'interaction', peak: -24, cooldown: 150, vary: 0.18, weight: 0.4 },
  'ui.hover':      { voice: 'technical', bus: 'interaction', peak: -36, cooldown: 180, vary: 0.3, weight: 0.08, hover: true },
  'ui.building':   { voice: 'mechanism', bus: 'interaction', peak: -34, cooldown: 200, vary: 0.2, hover: true },
}

/**
 * The only ids that survive prefers-reduced-motion: a press the reader made.
 * Everything else on this page is decoration over an animation they have
 * asked not to see.
 */
const ESSENTIAL = new Set(['ui.click'])

const STORAGE_KEY = 'bytes:sound'
const MANIFEST = '/assets/education/audio/manifest.json'

/* ---------------------------------------------------------- sustained beds */
/**
 * Three layers, all levelled rather than started and stopped, because the
 * reader crosses every one of their boundaries in both directions.
 *
 *   room     the quiet space the whole journey happens in
 *   growth   tension under the tree, rising as the growth front climbs
 *   distant  the campus, heard through the foliage before it is seen
 */
const room = bed('room', {
  voice: 'quietSpace',
  bus: 'ambience',
  peak: AMBIENCE_PEAK,
  trim: AMBIENCE_TRIM,
})

const growth = bed('growth', {
  voice: 'growthBed',
  bus: 'organic',
  peak: GROWTH_PEAK,
  trim: GROWTH_TRIM,
  epsilon: 0.03,
})

const distant = bed('distant', {
  voice: 'distantPlace',
  bus: 'ambience',
  peak: DISTANT_PEAK,
  trim: DISTANT_TRIM,
  epsilon: 0.03,
})

/**
 * The four formations, and the air.
 *
 * Every one of these is levelled every frame rather than triggered, because
 * every one of them is something the reader is *watching happen*. The first
 * version fired one-shots at milestones, and the result was a tree that built
 * itself in silence between four isolated noises — which reads as broken, not
 * as restrained. If it is forming on screen, it is sounding.
 */
const wood = bed('wood', {
  voice: 'woodForm',
  bus: 'organic',
  peak: WOOD_PEAK,
  trim: WOOD_TRIM,
  epsilon: 0.015,
})

const leaves = bed('leaves', {
  voice: 'leafForm',
  bus: 'organic',
  peak: LEAF_PEAK,
  trim: LEAF_TRIM,
  epsilon: 0.015,
})

const campus = bed('campus', {
  voice: 'campusForm',
  bus: 'transitions',
  peak: CAMPUS_PEAK,
  trim: CAMPUS_TRIM,
  epsilon: 0.02,
})

const air = bed('air', {
  voice: 'airMove',
  bus: 'transitions',
  peak: AIR_PEAK,
  trim: AIR_TRIM,
  // Finer than the others: this one tracks camera velocity, and a coarse gate
  // would make a smooth move sound stepped.
  epsilon: 0.01,
})

/** Wood and branches coming into existence, 0..1. */
export function woodLevel(v) {
  wood.level(v)
}

/** Foliage filling in, 0..1. */
export function leafLevel(v) {
  leaves.level(v)
}

/** The college resolving, 0..1. */
export function campusLevel(v) {
  campus.level(v)
}

/** How hard the camera is travelling, 0..1. */
export function airLevel(v) {
  air.level(v)
}

/** How much tension is under the tree, 0..1. Silence at 0. */
export function growthLevel(v) {
  growth.level(v)
}

/** How close the campus is, 0..1. Silence at 0. */
export function distantLevel(v) {
  distant.level(v)
}

/* -------------------------------------------------------------------- api */
export function initAudio() {
  configureAudio({
    storageKey: STORAGE_KEY,
    // The preference is one answer for the whole site. Someone who turned
    // sound on while reading /construction-two has answered this question
    // already and must not be asked again here.
    legacyKeys: ['c2:sound'],
    master: MASTER,
    buses: BUS_LEVELS,
    sounds: SOUNDS,
    essential: ESSENTIAL,
    calibration: CALIBRATION,
    voices: VOICES,
    manifest: MANIFEST,
    confirmId: 'ui.click',
    onAudible: (live) => (live ? room.level(1) : room.stop()),
  })
}

export {
  audioState,
  createChain,
  hasPref,
  isAudible,
  setEnabled,
  sound,
  subscribe,
  teardownAudio,
  toggleEnabled,
}

/** For the calibration tool and the policy tests. */
export const __mix = {
  SOUNDS,
  BUS_LEVELS,
  MASTER,
  AMBIENCE_PEAK,
  DISTANT_PEAK,
  GROWTH_PEAK,
  WOOD_PEAK,
  LEAF_PEAK,
  CAMPUS_PEAK,
  AIR_PEAK,
  dbToGain,
}
