/* GENERATED by tools/calibrate_education_audio.mjs — do not edit by hand.
 *
 * Per-sound corrections that make the dBFS targets in AudioManager.js true.
 * Measured through the real graph; see the tool for why this is per sound id
 * rather than per voice. Worst residual at generation: 1.02 dB.
 */
export const CALIBRATION = {
  'seed.stir': 1.4025,
  'seed.open': 1.4689,
  'grow.roots': 1.3664,
  'prop.tung': 0.4915,
  'disc.technology': 2.8054,
  'disc.science': 0.8267,
  'disc.design': 1.2569,
  'disc.engineering': 1.9060,
  'disc.business': 0.4644,
  'disc.resolved': 0.6913,
  'museum.enter': 0.4173,
  'museum.stop': 0.8629,
  'museum.settle': 0.6947,
  'artifact.paper': 1.2159,
  'artifact.glass': 0.8337,
  'artifact.tech': 3.2069,
  'connect.left': 0.5059,
  'connect.right': 0.5055,
  'connect.join': 0.5148,
  'glimpse.sense': 0.6183,
  'reveal.open': 0.4640,
  'reveal.campus': 0.5915,
  'reveal.near': 1.0609,
  'future.settle': 0.6848,
  'ui.click': 2.6465,
  'ui.hover': 5.7179,
  'ui.building': 1.9654,
}

export const AMBIENCE_TRIM = 0.9992
export const DISTANT_TRIM = 0.9043
export const GROWTH_TRIM = 0.5523
export const WOOD_TRIM = 1.4774
export const LEAF_TRIM = 0.5100
export const CAMPUS_TRIM = 0.5537
export const AIR_TRIM = 1.2594
