import { VOICES } from './voices.js'
import {
  bed,
  configureAudio,
  createChain,
  dbToGain,
  hasPref,
  isAudible,
  audioState,
  setEnabled,
  sound,
  subscribe,
  teardownAudio,
  toggleEnabled,
} from '../../../audio/engine.js'
// A namespace import rather than named ones, on purpose. calibration.js is
// generated by a tool that imports this file, so a named import of something
// the current calibration.js does not export yet is a syntax error that
// prevents the tool from running and regenerating it — a deadlock every time
// a new sustained voice is added. Unity is the right fallback: uncalibrated
// means "play it as written", not "fail".
import * as CAL from './calibration.js'

/**
 * This page's mix: which moments exist, what each one sounds like, and exactly
 * how loud it ends up.
 *
 * The machinery underneath — the context, the buses, the ceiling, cooldowns,
 * the preference, the unlock — moved to `src/audio/engine.js` when a second
 * route needed sound. Nothing about the behaviour changed in the move; the
 * rules were learned here and the engine still enforces them. What stays here
 * is everything that is true of THIS page and no other.
 *
 * Everything on the page calls `sound(id)` and nothing else. Which voice that
 * is, how loud, on which bus, and how often it is allowed to repeat all live
 * in the table below, so the whole mix can be read and changed in one place
 * rather than being spread across a dozen components.
 *
 * FOUR RULES THIS ENFORCES, BECAUSE NO CALLER SHOULD HAVE TO THINK ABOUT THEM
 *
 *   Nothing before a gesture. The context is not constructed until the first
 *   pointerdown, touch or key. Until then every `sound()` is a no-op that
 *   returns silently — no queueing, no "play it when we're allowed", because
 *   a burst of held-back sounds arriving at once is worse than silence.
 *
 *   Nothing twice. Every id carries a cooldown. Scrolling a pinned section at
 *   speed fires its thresholds in a few frames; the cooldown is what turns
 *   that into one click instead of nine.
 *
 *   Nothing loud. Master runs into a compressor with a low threshold, so even
 *   if several sections resolve on the same frame the sum cannot spike. The
 *   ceiling is structural, not a promise.
 *
 *   Nothing at all, if the page would rather not. Reduced motion drops
 *   everything except the click under a deliberate press. A coarse pointer
 *   drops every hover id. A blocked or unavailable AudioContext disables the
 *   system and the page never notices.
 */

const CALIBRATION = CAL.CALIBRATION ?? {}
const AMBIENCE_TRIM = CAL.AMBIENCE_TRIM ?? 1
const ASSEMBLY_TRIM = CAL.ASSEMBLY_TRIM ?? 1

/* -------------------------------------------------------------------- mix */
/**
 * Loudness is measured, not guessed.
 *
 * `calibration.js` is generated by `tools/calibrate_audio.mjs`, which renders
 * every sound below through this exact graph — same buses, same master, same
 * compressor — ten times, takes the median peak, and works out the correction
 * that makes it hit the dBFS figure the table claims. Every sound currently
 * lands within about 1 dB of its target, which is inside the voices' own
 * run-to-run jitter.
 *
 * This matters because per-voice normalisation is not enough: a click at
 * weight 0.55 carries an extra partial and sits 8 dB above the same click at
 * weight 0.1. The correction has to be per sound, not per voice.
 *
 * Change a voice or a target, re-run the tool, commit the result.
 */

const BUS_LEVELS = {
  ambience: 0.20,
  interaction: 0.30,
  construction: 0.25,
  transitions: 0.20,
}

const MASTER = 0.15

/* ----------------------------------------------------------------- sounds */
/**
 * The semantic layer. Sections name a moment; this decides what a moment
 * sounds like, and — more usefully — exactly how loud it ends up.
 *
 * `peak` is the target peak of this sound AT THE SPEAKER, in dBFS, after the
 * bus and the master have been applied. That is a deliberate departure from
 * the usual `gain: 0.05` style, and it is worth the departure: a bare 0.05
 * means nothing until you have also traced the bus and the master and the
 * loudness of the source, which is how a sound design ends up either
 * inaudible or shouting. Written this way the table is the mix. You can read
 * down the column and see that a hover is 10 dB under a click, that a click
 * is 8 dB under a structural hit, and that the room tone is 16 dB under
 * everything — and change any of it by moving one number.
 *
 * For scale: a normalised UI click sample played at full gain peaks around
 * -8 dBFS. Nothing here goes above -30.
 *
 * `weight`, `rate` and `dur` pass through to the voice. `vary` widens the
 * random spread on rate for ids that fire often — the brief asks for two or
 * three variations of each click to avoid the tell of a repeated sample;
 * synthesis makes the variation continuous instead of picking from three.
 */
const SOUNDS = {
  // hero -------------------------------------------------------------
  'hero.chapter':     { voice: 'paperPlace', bus: 'transitions',  peak: -15, cooldown: 700, vary: 0.10 },
  'hero.chapter.alt': { voice: 'paperMove',  bus: 'transitions',  peak: -17, cooldown: 700, vary: 0.12 },
  'hero.camera':      { voice: 'mechanical', bus: 'transitions',  peak: -16, cooldown: 700, vary: 0.08, dur: 0.42 },
  'hero.air':         { voice: 'air',        bus: 'transitions',  peak: -19, cooldown: 700, vary: 0.12 },

  // the sheet arriving on the desk ------------------------------------
  'card.place':       { voice: 'paperPlace', bus: 'construction', peak: -16, cooldown: 500, vary: 0.10 },

  // the pen ----------------------------------------------------------
  'pen.down':         { voice: 'pencil',     bus: 'construction', peak: -18, cooldown: 90,  vary: 0.18, dur: 0.09 },
  'pen.stroke':       { voice: 'pencil',     bus: 'construction', peak: -21, cooldown: 70,  vary: 0.22 },
  'pen.corner':       { voice: 'click',      bus: 'construction', peak: -25, cooldown: 80,  vary: 0.20, weight: 0.18 },

  // the building arriving ---------------------------------------------
  //
  // Two levels. The four `build.*` ids are accents — the first piece of each
  // phase to land, so the run has punctuation. The `piece.*` ids are every
  // other piece, 8 to 10 dB under them and on a short cooldown, which is what
  // turns thirteen separate taps into something assembling.
  // The four accents sit level with each other rather than descending. An
  // earlier cut had them at -33/-33/-35/-38 and the assembly audibly ran out
  // of energy: the loudest thing in the building going up was the first piece
  // of the foundation. Density is what rises here — more pieces, and the bed
  // under them thickening — not volume.
  // Mass carries far more energy than a tap at the same peak, and this one
  // lands first — at -33 the assembly opened on its loudest moment and
  // everything after it was a diminuendo.
  'build.foundation': { voice: 'concrete',   bus: 'construction', peak: -17, cooldown: 60, vary: 0.08 },
  'build.structure':  { voice: 'structural', bus: 'construction', peak: -15, cooldown: 60, vary: 0.10 },
  'build.envelope':   { voice: 'metal',      bus: 'construction', peak: -15, cooldown: 60, vary: 0.10 },
  'build.completion': { voice: 'click',      bus: 'construction', peak: -17, cooldown: 60, vary: 0.14, weight: 0.45 },
  // 20ms, which is a backstop rather than a gate. Building.jsx latches each
  // piece, so fourteen pieces make at most fourteen sounds however fast you
  // scroll — the cooldown only has to stop a hard flick landing several of
  // them inside a single frame. The previous 70ms was doing real damage: over
  // a 1680vh hero the fourteen pieces land roughly 120px of scroll apart, so
  // at any ordinary reading speed most of the building went up in silence and
  // you heard two or three beams out of fourteen.
  'piece.foundation': { voice: 'concrete',   bus: 'construction', peak: -22, cooldown: 20, vary: 0.16 },
  'piece.structure':  { voice: 'structural', bus: 'construction', peak: -22, cooldown: 20, vary: 0.18 },
  'piece.envelope':   { voice: 'metal',      bus: 'construction', peak: -23, cooldown: 20, vary: 0.18 },
  'piece.completion': { voice: 'click',      bus: 'construction', peak: -25, cooldown: 20, vary: 0.22, weight: 0.25 },
  // Coming apart. One id for all four phases, coloured by rate at the call
  // site. Level with a landing on peak, not under it: it has almost no energy
  // below 250Hz where the landings put two thirds of theirs, so matching them
  // on peak still leaves it obviously the lighter event. Trimmed 5 dB below
  // that it measured 14 dB down in energy and would have disappeared.
  'piece.lift':       { voice: 'release',    bus: 'construction', peak: -23, cooldown: 20, vary: 0.2 },
  'build.complete':   { voice: 'resolved',   bus: 'construction', peak: -16, cooldown: 1500 },

  // scroll thresholds --------------------------------------------------
  'scroll.mark':      { voice: 'click',      bus: 'transitions',  peak: -23, cooldown: 450, vary: 0.22, weight: 0.3 },

  // selected work ------------------------------------------------------
  'work.enter':       { voice: 'paperMove',  bus: 'transitions',  peak: -18, cooldown: 900, vary: 0.10 },
  'work.change':      { voice: 'air',        bus: 'transitions',  peak: -17, cooldown: 600, vary: 0.12 },
  'work.change.body': { voice: 'structural', bus: 'transitions',  peak: -21, cooldown: 600, vary: 0.14 },
  'work.hover':       { voice: 'click',      bus: 'interaction',  peak: -28, cooldown: 220, vary: 0.25, weight: 0.12, hover: true },

  // stats ---------------------------------------------------------------
  'stat.resolve':     { voice: 'measure',    bus: 'interaction',  peak: -19, cooldown: 220, vary: 0.08 },
  'stat.hover':       { voice: 'click',      bus: 'interaction',  peak: -29, cooldown: 200, vary: 0.25, weight: 0.1,  hover: true },

  // process -------------------------------------------------------------
  'process.plan':       { voice: 'pencil',     bus: 'construction', peak: -17, cooldown: 400, vary: 0.12, dur: 0.13 },
  'process.coordinate': { voice: 'click',      bus: 'construction', peak: -17, cooldown: 400, vary: 0.12, weight: 0.5 },
  'process.build':      { voice: 'structural', bus: 'construction', peak: -15, cooldown: 400, vary: 0.12 },
  'process.deliver':    { voice: 'resolved',   bus: 'construction', peak: -17, cooldown: 1200 },

  // the corners of the drawn route ----------------------------------------
  'draw.segment':     { voice: 'click',      bus: 'construction', peak: -27, cooldown: 400, vary: 0.24, weight: 0.18 },

  // the structural frame beside the statement -------------------------------
  'frame.datum':      { voice: 'click',      bus: 'construction', peak: -25, cooldown: 450, vary: 0.2,  weight: 0.22 },
  'frame.columns':    { voice: 'structural', bus: 'construction', peak: -20, cooldown: 450, vary: 0.14 },
  'frame.beams':      { voice: 'concrete',   bus: 'construction', peak: -18, cooldown: 450, vary: 0.12 },
  'frame.envelope':   { voice: 'metal',      bus: 'construction', peak: -18, cooldown: 450, vary: 0.12 },
  'frame.done':       { voice: 'resolved',   bus: 'construction', peak: -18, cooldown: 2000 },

  // the site plan, and the end of the page -----------------------------------
  'plan.done':        { voice: 'resolved',   bus: 'construction', peak: -17, cooldown: 2000 },

  // links and buttons ---------------------------------------------------------
  'ui.click':         { voice: 'click',      bus: 'interaction',  peak: -20, cooldown: 150, vary: 0.18, weight: 0.4 },
  'ui.hover':         { voice: 'click',      bus: 'interaction',  peak: -32, cooldown: 180, vary: 0.3,  weight: 0.08, hover: true },
}

/** The room tone's target, on the same scale. 16 dB under the quietest hit. */
const AMBIENCE_PEAK = -40

/**
 * The assembly bed at full density — i.e. with the whole building standing.
 * Under the pieces landing on top of it, and well under a click.
 */
const ASSEMBLY_PEAK = -30


/* The only ids that survive prefers-reduced-motion: a press the user made. */
const ESSENTIAL = new Set(['ui.click'])

const STORAGE_KEY = 'bytes:sound'
const MANIFEST = '/assets/construction-two/audio/manifest.json'

/* ---------------------------------------------------------- sustained beds */
/**
 * The room the film happens in, and the low bed under the building going up.
 *
 * Both are levelled rather than started and stopped, because a reader
 * scrolling back and forth across the same boundary would otherwise start and
 * stop an oscillator repeatedly — wasteful, and audible.
 */
const roomTone = bed('roomTone', {
  voice: 'roomTone',
  bus: 'ambience',
  peak: AMBIENCE_PEAK,
  trim: AMBIENCE_TRIM,
})

const assemblyBed = bed('assembly', {
  voice: 'assembly',
  bus: 'construction',
  peak: ASSEMBLY_PEAK,
  trim: ASSEMBLY_TRIM,
  epsilon: 0.02,
})

/**
 * How much of the building is standing, 0..1. Silence at 0.
 *
 * Kept as a named export rather than exposing the bed, because RoomViewer
 * calls this every frame the hero is live and the call site should say what
 * the number means.
 */
export function assemblyLevel(v) {
  assemblyBed.level(v)
}

/* ------------------------------------------------------------------- api */
/**
 * Hand this page's mix to the engine, then let it read the environment and the
 * stored preference. Creates nothing — no context, no listeners.
 *
 * `legacyKeys` matters: this route stored its preference under `c2:sound`
 * before there was a second route to share it with. A visitor who already
 * answered must not be asked again because the key was renamed underneath
 * them, so the old answer is migrated on first read.
 */
export function initAudio() {
  configureAudio({
    storageKey: STORAGE_KEY,
    legacyKeys: ['c2:sound'],
    master: MASTER,
    buses: BUS_LEVELS,
    sounds: SOUNDS,
    essential: ESSENTIAL,
    calibration: CALIBRATION,
    voices: VOICES,
    manifest: MANIFEST,
    confirmId: 'ui.click',
    // The room tone follows audibility exactly: on when sound is actually
    // coming out, gone the moment it is not.
    onAudible: (live) => (live ? roomTone.level(1) : roomTone.stop()),
  })
}

export {
  createChain,
  hasPref,
  isAudible,
  audioState,
  setEnabled,
  sound,
  subscribe,
  teardownAudio,
  toggleEnabled,
}

/** For the calibration tool and the policy tests. */
export const __mix = { SOUNDS, BUS_LEVELS, MASTER, AMBIENCE_PEAK, ASSEMBLY_PEAK, dbToGain }
