import { VOICES } from './voices.js'
// A namespace import rather than named ones, on purpose. calibration.js is
// generated by a tool that imports this file, so a named import of something
// the current calibration.js does not export yet is a syntax error that
// prevents the tool from running and regenerating it — a deadlock every time
// a new sustained voice is added. Unity is the right fallback: uncalibrated
// means "play it as written", not "fail".
import * as CAL from './calibration.js'

/**
 * The page's one audio context, and the only thing that is allowed to make a
 * sound.
 *
 * Everything on the page calls `sound(id)` and nothing else. Which voice that
 * is, how loud, on which bus, and how often it is allowed to repeat all live
 * in the table below, so the whole mix can be read and changed in one place
 * rather than being spread across a dozen components.
 *
 * FOUR RULES THIS ENFORCES, BECAUSE NO CALLER SHOULD HAVE TO THINK ABOUT THEM
 *
 *   Nothing before a gesture. The context is not constructed until the first
 *   pointerdown, touch or key. Until then every `sound()` is a no-op that
 *   returns silently — no queueing, no "play it when we're allowed", because
 *   a burst of held-back sounds arriving at once is worse than silence.
 *
 *   Nothing twice. Every id carries a cooldown. Scrolling a pinned section at
 *   speed fires its thresholds in a few frames; the cooldown is what turns
 *   that into one click instead of nine.
 *
 *   Nothing loud. Master runs into a compressor with a low threshold, so even
 *   if several sections resolve on the same frame the sum cannot spike. The
 *   ceiling is structural, not a promise.
 *
 *   Nothing at all, if the page would rather not. Reduced motion drops
 *   everything except the click under a deliberate press. A coarse pointer
 *   drops every hover id. A blocked or unavailable AudioContext disables the
 *   system and the page never notices.
 */

const CALIBRATION = CAL.CALIBRATION ?? {}
const AMBIENCE_TRIM = CAL.AMBIENCE_TRIM ?? 1
const ASSEMBLY_TRIM = CAL.ASSEMBLY_TRIM ?? 1

/* -------------------------------------------------------------------- mix */
/**
 * Loudness is measured, not guessed.
 *
 * `calibration.js` is generated by `tools/calibrate_audio.mjs`, which renders
 * every sound below through this exact graph — same buses, same master, same
 * compressor — ten times, takes the median peak, and works out the correction
 * that makes it hit the dBFS figure the table claims. Every sound currently
 * lands within about 1 dB of its target, which is inside the voices' own
 * run-to-run jitter.
 *
 * This matters because per-voice normalisation is not enough: a click at
 * weight 0.55 carries an extra partial and sits 8 dB above the same click at
 * weight 0.1. The correction has to be per sound, not per voice.
 *
 * Change a voice or a target, re-run the tool, commit the result.
 */

const BUS_LEVELS = {
  ambience: 0.20,
  interaction: 0.30,
  construction: 0.25,
  transitions: 0.20,
}

const MASTER = 0.15

/* ----------------------------------------------------------------- sounds */
/**
 * The semantic layer. Sections name a moment; this decides what a moment
 * sounds like, and — more usefully — exactly how loud it ends up.
 *
 * `peak` is the target peak of this sound AT THE SPEAKER, in dBFS, after the
 * bus and the master have been applied. That is a deliberate departure from
 * the usual `gain: 0.05` style, and it is worth the departure: a bare 0.05
 * means nothing until you have also traced the bus and the master and the
 * loudness of the source, which is how a sound design ends up either
 * inaudible or shouting. Written this way the table is the mix. You can read
 * down the column and see that a hover is 10 dB under a click, that a click
 * is 8 dB under a structural hit, and that the room tone is 16 dB under
 * everything — and change any of it by moving one number.
 *
 * For scale: a normalised UI click sample played at full gain peaks around
 * -8 dBFS. Nothing here goes above -30.
 *
 * `weight`, `rate` and `dur` pass through to the voice. `vary` widens the
 * random spread on rate for ids that fire often — the brief asks for two or
 * three variations of each click to avoid the tell of a repeated sample;
 * synthesis makes the variation continuous instead of picking from three.
 */
const SOUNDS = {
  // hero -------------------------------------------------------------
  'hero.chapter':     { voice: 'paperPlace', bus: 'transitions',  peak: -15, cooldown: 700, vary: 0.10 },
  'hero.chapter.alt': { voice: 'paperMove',  bus: 'transitions',  peak: -17, cooldown: 700, vary: 0.12 },
  'hero.camera':      { voice: 'mechanical', bus: 'transitions',  peak: -16, cooldown: 700, vary: 0.08, dur: 0.42 },
  'hero.air':         { voice: 'air',        bus: 'transitions',  peak: -19, cooldown: 700, vary: 0.12 },

  // the sheet arriving on the desk ------------------------------------
  'card.place':       { voice: 'paperPlace', bus: 'construction', peak: -16, cooldown: 500, vary: 0.10 },

  // the pen ----------------------------------------------------------
  'pen.down':         { voice: 'pencil',     bus: 'construction', peak: -18, cooldown: 90,  vary: 0.18, dur: 0.09 },
  'pen.stroke':       { voice: 'pencil',     bus: 'construction', peak: -21, cooldown: 70,  vary: 0.22 },
  'pen.corner':       { voice: 'click',      bus: 'construction', peak: -25, cooldown: 80,  vary: 0.20, weight: 0.18 },

  // the building arriving ---------------------------------------------
  //
  // Two levels. The four `build.*` ids are accents — the first piece of each
  // phase to land, so the run has punctuation. The `piece.*` ids are every
  // other piece, 8 to 10 dB under them and on a short cooldown, which is what
  // turns thirteen separate taps into something assembling.
  // The four accents sit level with each other rather than descending. An
  // earlier cut had them at -33/-33/-35/-38 and the assembly audibly ran out
  // of energy: the loudest thing in the building going up was the first piece
  // of the foundation. Density is what rises here — more pieces, and the bed
  // under them thickening — not volume.
  // Mass carries far more energy than a tap at the same peak, and this one
  // lands first — at -33 the assembly opened on its loudest moment and
  // everything after it was a diminuendo.
  'build.foundation': { voice: 'concrete',   bus: 'construction', peak: -17, cooldown: 60, vary: 0.08 },
  'build.structure':  { voice: 'structural', bus: 'construction', peak: -15, cooldown: 60, vary: 0.10 },
  'build.envelope':   { voice: 'metal',      bus: 'construction', peak: -15, cooldown: 60, vary: 0.10 },
  'build.completion': { voice: 'click',      bus: 'construction', peak: -17, cooldown: 60, vary: 0.14, weight: 0.45 },
  // 20ms, which is a backstop rather than a gate. Building.jsx latches each
  // piece, so fourteen pieces make at most fourteen sounds however fast you
  // scroll — the cooldown only has to stop a hard flick landing several of
  // them inside a single frame. The previous 70ms was doing real damage: over
  // a 1680vh hero the fourteen pieces land roughly 120px of scroll apart, so
  // at any ordinary reading speed most of the building went up in silence and
  // you heard two or three beams out of fourteen.
  'piece.foundation': { voice: 'concrete',   bus: 'construction', peak: -22, cooldown: 20, vary: 0.16 },
  'piece.structure':  { voice: 'structural', bus: 'construction', peak: -22, cooldown: 20, vary: 0.18 },
  'piece.envelope':   { voice: 'metal',      bus: 'construction', peak: -23, cooldown: 20, vary: 0.18 },
  'piece.completion': { voice: 'click',      bus: 'construction', peak: -25, cooldown: 20, vary: 0.22, weight: 0.25 },
  // Coming apart. One id for all four phases, coloured by rate at the call
  // site. Level with a landing on peak, not under it: it has almost no energy
  // below 250Hz where the landings put two thirds of theirs, so matching them
  // on peak still leaves it obviously the lighter event. Trimmed 5 dB below
  // that it measured 14 dB down in energy and would have disappeared.
  'piece.lift':       { voice: 'release',    bus: 'construction', peak: -23, cooldown: 20, vary: 0.2 },
  'build.complete':   { voice: 'resolved',   bus: 'construction', peak: -16, cooldown: 1500 },

  // scroll thresholds --------------------------------------------------
  'scroll.mark':      { voice: 'click',      bus: 'transitions',  peak: -23, cooldown: 450, vary: 0.22, weight: 0.3 },

  // selected work ------------------------------------------------------
  'work.enter':       { voice: 'paperMove',  bus: 'transitions',  peak: -18, cooldown: 900, vary: 0.10 },
  'work.change':      { voice: 'air',        bus: 'transitions',  peak: -17, cooldown: 600, vary: 0.12 },
  'work.change.body': { voice: 'structural', bus: 'transitions',  peak: -21, cooldown: 600, vary: 0.14 },
  'work.hover':       { voice: 'click',      bus: 'interaction',  peak: -28, cooldown: 220, vary: 0.25, weight: 0.12, hover: true },

  // stats ---------------------------------------------------------------
  'stat.resolve':     { voice: 'measure',    bus: 'interaction',  peak: -19, cooldown: 220, vary: 0.08 },
  'stat.hover':       { voice: 'click',      bus: 'interaction',  peak: -29, cooldown: 200, vary: 0.25, weight: 0.1,  hover: true },

  // process -------------------------------------------------------------
  'process.plan':       { voice: 'pencil',     bus: 'construction', peak: -17, cooldown: 400, vary: 0.12, dur: 0.13 },
  'process.coordinate': { voice: 'click',      bus: 'construction', peak: -17, cooldown: 400, vary: 0.12, weight: 0.5 },
  'process.build':      { voice: 'structural', bus: 'construction', peak: -15, cooldown: 400, vary: 0.12 },
  'process.deliver':    { voice: 'resolved',   bus: 'construction', peak: -17, cooldown: 1200 },

  // the corners of the drawn route ----------------------------------------
  'draw.segment':     { voice: 'click',      bus: 'construction', peak: -27, cooldown: 400, vary: 0.24, weight: 0.18 },

  // the structural frame beside the statement -------------------------------
  'frame.datum':      { voice: 'click',      bus: 'construction', peak: -25, cooldown: 450, vary: 0.2,  weight: 0.22 },
  'frame.columns':    { voice: 'structural', bus: 'construction', peak: -20, cooldown: 450, vary: 0.14 },
  'frame.beams':      { voice: 'concrete',   bus: 'construction', peak: -18, cooldown: 450, vary: 0.12 },
  'frame.envelope':   { voice: 'metal',      bus: 'construction', peak: -18, cooldown: 450, vary: 0.12 },
  'frame.done':       { voice: 'resolved',   bus: 'construction', peak: -18, cooldown: 2000 },

  // the site plan, and the end of the page -----------------------------------
  'plan.done':        { voice: 'resolved',   bus: 'construction', peak: -17, cooldown: 2000 },

  // links and buttons ---------------------------------------------------------
  'ui.click':         { voice: 'click',      bus: 'interaction',  peak: -20, cooldown: 150, vary: 0.18, weight: 0.4 },
  'ui.hover':         { voice: 'click',      bus: 'interaction',  peak: -32, cooldown: 180, vary: 0.3,  weight: 0.08, hover: true },
}

/** The room tone's target, on the same scale. 16 dB under the quietest hit. */
const AMBIENCE_PEAK = -40

/**
 * The assembly bed at full density — i.e. with the whole building standing.
 * Under the pieces landing on top of it, and well under a click.
 */
const ASSEMBLY_PEAK = -30

const dbToGain = (db) => 10 ** (db / 20)

/* The only ids that survive prefers-reduced-motion: a press the user made. */
const ESSENTIAL = new Set(['ui.click'])

const STORAGE_KEY = 'c2:sound'
const MANIFEST = '/assets/construction-two/audio/manifest.json'

/* ------------------------------------------------------------------ state */
let ctx = null
let master = null
let buses = null
// Read at module scope, not in initAudio(). React runs child effects before
// parent ones, so SoundButton subscribed before the page had called initAudio()
// and was handed this value — and when it said `true`, the control rendered its
// ON state on a page whose sound is off, which is a lie about the one thing it
// exists to report. `readPref` is a function declaration and so is hoisted.
let enabled = readPref()
let unlocked = false
let failed = false
let ambience = null
let assembly = null
let assemblyAt = -1
let reduced = false
let coarse = false
const last = new Map()
const samples = new Map()
const listeners = new Set()

/**
 * Off until asked. A page that starts making noise at someone is a page they
 * close, and the browser would refuse to do it anyway.
 */
function readPref() {
  try {
    return localStorage.getItem(STORAGE_KEY) === 'on'
  } catch {
    return false
  }
}

function writePref(on) {
  try {
    localStorage.setItem(STORAGE_KEY, on ? 'on' : 'off')
  } catch {
    /* private mode, blocked storage — the preference just won't persist */
  }
}

function notify() {
  for (const fn of listeners) fn({ enabled, unlocked, failed })
}

function media() {
  if (typeof matchMedia !== 'function') return
  reduced = matchMedia('(prefers-reduced-motion: reduce)').matches
  coarse = matchMedia('(hover: none)').matches
}

/* ------------------------------------------------------------------ graph */
/**
 * The output chain, built in one place.
 *
 * Exported because the calibration tool and the policy tests need the exact
 * same graph — they measure what this page will actually produce, and a
 * second hand-copied compressor in a tool file is a measurement of something
 * that does not exist. They had drifted once already.
 *
 *     bus → master → compressor → soft clip → destination
 *
 * The compressor catches several sections resolving together. Its threshold
 * sits well above the loudest single sound so it never touches individual
 * events — with it at -24 it was compressing every accent in the assembly,
 * which is both wrong musically and impossible to calibrate against, since
 * the correction feeds back into the gain reduction.
 *
 * The soft clip behind it is the actual ceiling. A compressor has an attack
 * time — 4ms here — and a stack of transients landing on one frame is through
 * it before it reacts; firing the entire palette at once measured +1.2 dBFS,
 * which is clipping. A waveshaper has no attack: tanh is transparent below
 * about -6 dBFS and mathematically cannot exceed 0.83, whatever arrives.
 */
export function createChain(ctx) {
  const comp = ctx.createDynamicsCompressor()
  comp.threshold.value = -12
  comp.knee.value = 12
  comp.ratio.value = 6
  comp.attack.value = 0.004
  comp.release.value = 0.2

  const clip = ctx.createWaveShaper()
  const n = 2048
  const curve = new Float32Array(n)
  for (let i = 0; i < n; i += 1) {
    const x = (i / (n - 1)) * 2 - 1
    curve[i] = Math.tanh(x * 1.2)
  }
  clip.curve = curve
  clip.oversample = '2x'

  const master = ctx.createGain()
  master.gain.value = MASTER
  master.connect(comp).connect(clip).connect(ctx.destination)

  const buses = {}
  for (const [name, level] of Object.entries(BUS_LEVELS)) {
    const g = ctx.createGain()
    g.gain.value = level
    g.connect(master)
    buses[name] = g
  }
  return { master, buses }
}

function build() {
  const Ctx = typeof AudioContext !== 'undefined'
    ? AudioContext
    : typeof webkitAudioContext !== 'undefined'
      ? webkitAudioContext          // eslint-disable-line no-undef
      : null
  if (!Ctx) {
    failed = true
    return false
  }

  try {
    ctx = new Ctx({ latencyHint: 'interactive' })
  } catch {
    failed = true
    return false
  }

  const chain = createChain(ctx)
  master = chain.master
  buses = chain.buses
  master.gain.value = enabled ? MASTER : 0
  return true
}

/**
 * Optional real recordings.
 *
 * One request for a manifest that is not there by default. If you add
 * `public/assets/construction-two/audio/manifest.json` mapping sound ids to
 * files, those ids play the recording and every other id stays synthesised —
 * so a single sound can be replaced without touching any of this.
 */
async function loadSamples() {
  let list
  try {
    const res = await fetch(MANIFEST, { cache: 'force-cache' })
    if (!res.ok) return
    list = await res.json()
  } catch {
    return                       // no manifest is the normal case
  }
  const base = MANIFEST.replace(/manifest\.json$/, '')
  await Promise.all(
    Object.entries(list).map(async ([id, file]) => {
      if (!SOUNDS[id]) return
      try {
        const res = await fetch(base + file)
        if (!res.ok) return
        samples.set(id, await ctx.decodeAudioData(await res.arrayBuffer()))
      } catch {
        /* a missing or undecodable file just leaves the voice synthesised */
      }
    }),
  )
}

/* ----------------------------------------------------------------- unlock */
/**
 * There is exactly one way sound starts on this page, and it is someone
 * pressing the button.
 *
 * An earlier version listened for pointerdown, touch, keys, and eventually
 * wheel and scroll, trying to start the audio the moment anything happened.
 * That was wrong in both directions: it made the page unpredictable — sound
 * arriving from a stray click you did not connect to sound — and it did not
 * even work, because the spec does not count scrolling as user activation and
 * this page is read by scrolling.
 *
 * Pressing a button is unambiguously a gesture, so this always succeeds, and
 * what starts the sound is the thing labelled "sound".
 */
function start(after) {
  if (failed) return false
  if (!ctx && !build()) {
    notify()
    return false
  }
  ctx.resume().then(() => {
    if (ctx.state !== 'running') return
    unlocked = true
    loadSamples()
    if (enabled && !reduced) startAmbience()
    notify()
    // Anything the press itself should make audible has to wait for this
    // point: resume() is async, so a sound fired straight after the click
    // would be dropped for not being unlocked yet.
    if (after) after()
  }).catch(() => {
    /* nothing to recover: the next press tries again */
  })
  return true
}

/* --------------------------------------------------------------- ambience */
function startAmbience() {
  if (!ctx || ambience || reduced) return
  ambience = VOICES.roomTone(ctx, buses.ambience, ctx.currentTime, {
    gain: (dbToGain(AMBIENCE_PEAK) / (BUS_LEVELS.ambience * MASTER)) * AMBIENCE_TRIM,
  })
}

function stopAmbience() {
  if (!ambience) return
  try {
    ambience(ctx.currentTime, 0.8)
  } catch {
    /* already torn down */
  }
  ambience = null
}

/* -------------------------------------------------------------- assembly */
/**
 * The low bed under the building going up.
 *
 * Built on demand the first time the scroll enters the assembly and left
 * running at zero afterwards, because tearing an oscillator down and building
 * it again every time the reader scrolls back and forth over the same 19% of
 * the film would be both wasteful and audible.
 *
 * `level` is how much of the building is standing, 0..1. Silence at 0.
 */
export function assemblyLevel(v) {
  if (!enabled || !unlocked || failed || !ctx || reduced) return
  if (!assembly) {
    try {
      assembly = VOICES.assembly(ctx, buses.construction, ctx.currentTime, {
        gain: (dbToGain(ASSEMBLY_PEAK) / (BUS_LEVELS.construction * MASTER)) * ASSEMBLY_TRIM,
      })
    } catch {
      assembly = null
      return
    }
  }
  // Only tell the graph about changes it can hear. At 60fps an unconditional
  // setTargetAtTime is 60 pointless scheduled ramps a second.
  if (Math.abs(v - assemblyAt) < 0.02) return
  assemblyAt = v
  try {
    assembly.level(v)
  } catch {
    /* context went away underneath us */
  }
}

function stopAssembly() {
  if (!assembly) return
  try {
    assembly.stop(ctx.currentTime, 0.6)
  } catch {
    /* already torn down */
  }
  assembly = null
  assemblyAt = -1
}

/* ------------------------------------------------------------------- play */
/**
 * Play a named moment. Safe to call at any time, from anywhere, before the
 * context exists, after teardown, on a blocked browser, in a headless test.
 * It returns a boolean only so callers can assert in tests; nothing on the
 * page reads it.
 */
export function sound(id, opts = {}) {
  const spec = SOUNDS[id]
  if (!spec || !enabled || !unlocked || failed || !ctx) return false
  if (reduced && !ESSENTIAL.has(id)) return false
  if (coarse && spec.hover) return false

  const now = performance.now()
  // `has` rather than `|| 0`: a sound that has never played must not be
  // treated as having played at time zero. It only ever mattered on a clock
  // whose origin is near zero — but that is exactly the clock a test rig
  // provides, and a rule that is only true because the numbers happen to be
  // big is not a rule.
  const prev = last.has(id) ? last.get(id) : -Infinity
  const cooldown = opts.cooldown ?? spec.cooldown ?? 120
  if (now - prev < cooldown) return false
  last.set(id, now)

  const bus = buses[spec.bus] || buses.interaction
  const t = ctx.currentTime + (opts.delay || 0)
  const vary = spec.vary || 0
  const rate = (opts.rate ?? 1) * (1 + (Math.random() * 2 - 1) * vary)
  // Undo the bus and the master so the number in the table is what actually
  // comes out of the speaker. The voice trims make `gain` mean peak
  // amplitude, so this is the whole conversion.
  const busLevel = BUS_LEVELS[spec.bus] ?? BUS_LEVELS.interaction
  const target = dbToGain(opts.peak ?? spec.peak) / (busLevel * MASTER)
  // Level jitter is deliberately narrower than rate jitter: a click that
  // changes loudness run to run reads as a fault, one that changes colour
  // reads as a hand.
  const gain = target * (0.92 + Math.random() * 0.16)

  try {
    const buffer = samples.get(id)
    if (buffer) {
      const src = ctx.createBufferSource()
      src.buffer = buffer
      src.playbackRate.value = rate
      const g = ctx.createGain()
      g.gain.value = gain
      src.connect(g).connect(bus)
      src.start(t)
      return true
    }

    const voice = VOICES[spec.voice]
    if (!voice) return false
    voice(ctx, bus, t, {
      ...spec,
      ...opts,
      rate,
      gain: gain * (CALIBRATION[id] ?? 1),
    })
    return true
  } catch {
    return false                 // a bad frame must never break the page
  }
}

/* ------------------------------------------------------------------- api */
/** Read the environment and the stored preference. Creates nothing. */
export function initAudio() {
  if (unlocked || failed || ctx) return
  media()
  // Re-read rather than trust the module's first look: another tab may have
  // written the preference since this module was evaluated.
  enabled = readPref()
  notify()
}

/**
 * Has this visitor ever answered the question?
 *
 * Only used to decide whether the control should draw attention to itself. A
 * first-time visitor gets the invitation; someone who has already turned sound
 * off has answered, and being nudged again is nagging.
 */
export function hasPref() {
  try {
    return localStorage.getItem(STORAGE_KEY) !== null
  } catch {
    return true
  }
}

export function setEnabled(on) {
  enabled = !!on
  writePref(enabled)
  if (master) {
    const t = ctx.currentTime
    master.gain.cancelScheduledValues(t)
    master.gain.setValueAtTime(master.gain.value, t)
    master.gain.linearRampToValueAtTime(enabled ? MASTER : 0.0001, t + 0.25)
  }
  if (enabled) {
    if (unlocked) startAmbience()
  } else {
    stopAmbience()
    stopAssembly()
  }
  notify()
}

export function toggleEnabled() {
  // A stored preference is not a state. Nothing on this page is audible until
  // a gesture has unlocked the context, so a visitor arriving with 'on' saved
  // has the wish but not the sound — and the first press there must START it,
  // not mute it. Without this the press writes 'off' over a preference nobody
  // withdrew, stays silent, and takes a second press to do what the first one
  // looked like it would do.
  if (enabled && !unlocked && !failed) {
    start(() => sound('ui.click'))
    return true
  }
  const next = !enabled
  setEnabled(next)
  // The press itself is the activation, so this is where the context gets
  // built and resumed — the first time, and after any later mute.
  if (next) start(() => sound('ui.click'))
  return next
}

/**
 * Is sound actually coming out?
 *
 * Distinct from `enabled`, which is only what the visitor last asked for. A
 * page reloaded with 'on' saved has `enabled` true and nothing playing, and a
 * control that reads the preference rather than this reports itself as on over
 * a silent page — which is exactly what it did.
 */
export function isAudible() {
  return enabled && unlocked && !failed
}

export function audioState() {
  return { enabled, unlocked, failed, reduced, coarse }
}

export function subscribe(fn) {
  listeners.add(fn)
  fn({ enabled, unlocked, failed })
  return () => listeners.delete(fn)
}

export function teardownAudio() {
  stopAmbience()
  stopAssembly()
  listeners.clear()
  last.clear()
  samples.clear()
  if (ctx) {
    try {
      ctx.close()
    } catch {
      /* already closed */
    }
  }
  ctx = null
  master = null
  buses = null
  unlocked = false
  ambience = null
  assembly = null
  assemblyAt = -1
}

/** Exposed for the test harness only. */
export const __mix = { SOUNDS, BUS_LEVELS, MASTER, AMBIENCE_PEAK, ASSEMBLY_PEAK, dbToGain }
